# pragma once

#include <systemc.h>
#include <math.h>
#include <iostream>
#include <fstream>
using namespace std;

/*
 * Robotic arm simulation. 
 * This module simulates the motion of of the robotic arm in 2D space.
 * The robotic arm recieves as input the torque generated by the motor.
 * The output of the module is the angular displacement of the arm, 
 * which is read by a sensor. 
 */
SC_MODULE(robot_arm) {
	//Ports
	sc_in <bool> clk;

	//time
	float dt = 0.0;	 			// Delta time [s]
	float time = 0.0; 			// Time [s]

	//constants
	float const g = -9.81; 		// Gravity [m/s²]
	float const r = 0.8; 		// Length of robot arm [m]
	float const F_c = 0.1; 		// Coulomb friction factor [None]
	float const F_v = 0.05; 	// Viscous friction factor [None]
	float const m = 1.2; 		// Mass of end effector [kg]

	//variables
	float q_ddot = 0.0;			// Angular acceleartion [rad/s²]
	float q_dot = 0.0;			// Angular velocity [rad/s]
	float q = 0.0;				// Angular displacement [rad]
	float g_tau = 0.0;			// Torque due to gravity [N*m]
	float F_tau = 0.0;			// Torque due to friction [N*m]
	float interia = m * r*r;	// Mass moment of inertia [kg*m²]
	float motor_tau = 0.0; 		// Torque from the motor [N*m]

	//inputs
	sc_in<float> in_motor_tau; 			

	//outputs
	sc_out<float> out_q;

	//file
	ofstream myfile;

	void step();

	//Constructor
	SC_CTOR(robot_arm) {
		
		myfile.open ("output.txt");
		//Process Registration
		SC_CTHREAD(step, clk.pos());
	}

	~robot_arm(){
		myfile.close();
	}
};
